import os
from datetime import datetime
from dotenv import load_dotenv
from tools.llm_client import call_llm

load_dotenv()
def clean_float(val) -> str:
    """Converts np.float64 or float to clean string."""
    try:
        return str(round(float(val), 1))
    except:
        return str(val)

def run_memo_writer_agent(
    financials_result: dict,
    news_result: dict,
    sentiment_result: dict
) -> dict:
    """
    Memo Writer Agent — the orchestrating brain.
    Takes outputs from all 3 agents and synthesizes them into
    a structured investment memo suitable for a Portfolio Manager.
    """

    print(f"\n Memo Writer Agent starting...")

    ticker = financials_result["ticker"]
    company_name = financials_result["company_name"]
    sector = financials_result["sector"]
    date = datetime.today().strftime("%B %d, %Y")

    # Extract key metrics for the prompt
    raw = financials_result["raw_data"]
    valuation = raw["valuation"]
    financials = raw["financials"]
    price = raw["price"]
    analyst = raw["analyst"]

    dataset_signal = sentiment_result["dataset_signal"]
    baseline = sentiment_result["baseline"]

    prompt = f"""
You are a senior research analyst at a top-tier hedge fund.
Write a complete, professional investment research memo for presentation
to the Portfolio Manager. This memo should be based strictly on the
analysis provided below from three specialized agents.

---
## INPUTS FROM RESEARCH AGENTS

### FINANCIALS AGENT OUTPUT
{financials_result['analysis']}

Price History: {financials_result['price_history']}

Key Metrics:
- Market Cap: ${clean_float(valuation['market_cap_B'])}B
- Revenue: ${clean_float(financials['revenue_B'])}B  
- Gross Margin: {clean_float(financials['gross_margin_pct'])}%
- Operating Margin: {clean_float(financials['operating_margin_pct'])}%
- P/E Ratio: {valuation['pe_ratio']}
- Free Cash Flow: ${clean_float(financials['free_cashflow_B'])}B
- Beta: {price['beta']}
- Analyst Target: ${analyst['target_price']}
- Recommendation: {analyst['recommendation']}

### NEWS AGENT OUTPUT
{news_result['analysis']}

### SENTIMENT AGENT OUTPUT
{sentiment_result['analysis']}

Dataset Signal (vs baseline):
- Positive: {clean_float(dataset_signal['positive_pct'])}% (baseline: {clean_float(baseline['positive_pct'])}%)
- Negative: {clean_float(dataset_signal['negative_pct'])}% (baseline: {clean_float(baseline['negative_pct'])}%)
- Neutral: {clean_float(dataset_signal['neutral_pct'])}% (baseline: {clean_float(baseline['neutral_pct'])}%)

---
Write the investment memo using EXACTLY this structure:


═══════════════════════════════════════════════════════════
INVESTMENT RESEARCH MEMO
═══════════════════════════════════════════════════════════
Company:        {company_name} ({ticker})
Sector:         {sector}
Date:           {date}
Prepared by:    Multi-Agent Research System v1.0
Classification: CONFIDENTIAL — FOR INTERNAL USE ONLY
═══════════════════════════════════════════════════════════

## 1. EXECUTIVE SUMMARY
(3-4 sentences. The single most important thing a PM needs to know.
Include overall stance: Bullish / Bearish / Neutral with conviction level.)
## 2. INVESTMENT THESIS
(The core reason to own or avoid this stock. 2-3 sharp paragraphs.
Reference specific financial metrics and news catalysts.)

## 3. FINANCIAL SNAPSHOT
(Present key metrics in a clean table format, followed by 2-3 sentences
of interpretation. Highlight what stands out vs sector norms.)

## 4. NEWS & CATALYST ANALYSIS
(Summarize the most important recent developments.
What events could move the stock in the next 30-90 days?)


## 5. SENTIMENT ANALYSIS
(Combine the dataset signal with live news sentiment.
Be specific about what the data shows vs the market baseline.)

## 6. KEY RISKS
(List and briefly explain the top 4 risks. Be specific, not generic.)

## 7. KEY STRENGTHS  
(List and briefly explain the top 4 strengths. Reference actual numbers.)


## 8. VALUATION ASSESSMENT
(Is the stock cheap, fair value, or expensive at current levels?
What would make it more/less attractive?)

## 9. RECOMMENDATION
(Clear stance: BUY / SELL / HOLD with target price range.
What are the conditions that would change this view?)

## 10. MONITORING CHECKLIST
(5 specific metrics or events to watch in the next quarter.
Each should be measurable and time-bound.)


═══════════════════════════════════════════════════════════
DISCLAIMER: This memo was generated by an AI multi-agent 
research system for portfolio management purposes. All 
investment decisions require human review and approval.
═══════════════════════════════════════════════════════════

Use professional financial language throughout.
Be specific — reference actual numbers from the agent outputs.
Avoid generic statements — every claim must be backed by data.
"""
    memo = call_llm(prompt, max_tokens=4000)

    # Save memo to file
    filename = f"output/memos/{ticker}_{datetime.today().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename, "w") as f:
        f.write(memo)

    print(f" Memo Writer Agent complete")
    print(f" Memo saved to: {filename}")

    return {
        "ticker": ticker,
        "company_name": company_name,
        "memo": memo,
        "saved_to": filename,
        "status": "success"
    }

# Quick test
if __name__ == "__main__":
    # We need all 3 agents to test this — run from main.py instead
    print(" Memo Writer Agent requires outputs from all 3 agents.")
    print("Run main.py to test the full pipeline.")    



